language: go

go:
  - 1.6
  - 1.7
  - master

go_import_path: github.com/corywalker/expreduce

install:
  - go get -d ./...
  - go get golang.org/x/tools/cmd/goyacc
  - go get github.com/cznic/golex
  - go get -u github.com/jteeuwen/go-bindata/...
  - go generate ./...
  - go get ./...

script:
  - go test -v ./...
